version: '3.8'

services:
  n8n:
    build: .
    container_name: n8n
    hostname: n8n
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 5678:5678
    volumes:
      - /volume2/docker/config/n8n/data:/home/node/.n8n:rw
      - /volume2/docker/config/n8n/files:/files:rw
    environment:
      N8N_HOST: n8n.cloutio.synology.me
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_URL: https://n8n.cloutio.synology.me
      GENERIC_TIMEZONE: Europe/Amsterdam
      TZ: Europe/Amsterdam
      N8N_EMAIL_MODE: smtp
      N8N_SMTP_HOST: smtp.gmail.com
      N8N_SMTP_PORT: 587
      N8N_SMTP_SENDER: r.clout@gmail.com
      N8N_SMTP_USER: r.clout@gmail.com
      N8N_SMTP_PASS: gecppeevapmtuzvu
    restart: always
